## YAML Template.
---
quarkus:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: neo4j

  arc:
    transform-unproxyable-classes: true
  swagger-ui:
        always-include: true
